#include "../include/canalize/item/Items.h"

namespace Canalize {
    namespace Item {
        const Item Items::AIR(0, "air", 0);
        const Item Items::STONE(1, "stone");
        const Item Items::GRASS_BLOCK(2, "grass_block");
        const Item Items::DIRT(3, "dirt");
        const Item Items::COBBLESTONE(4, "cobblestone");
        const Item Items::PLANKS(5, "planks");
        const Item Items::SAPLING(6, "sapling");
        const Item Items::BEDROCK(7, "bedrock");
        const Item Items::WATER_BUCKET(8, "water_bucket", 1);
        const Item Items::LAVA_BUCKET(9, "lava_bucket", 1);
        const Item Items::SAND(12, "sand");
        const Item Items::GRAVEL(13, "gravel");
        const Item Items::GOLD_ORE(14, "gold_ore");
        const Item Items::IRON_ORE(15, "iron_ore");
        const Item Items::COAL_ORE(16, "coal_ore");
        const Item Items::LOG(17, "log");
        const Item Items::LEAVES(18, "leaves");
        const Item Items::SPONGE(19, "sponge");
        const Item Items::GLASS(20, "glass");
        const Item Items::IRON_SHOVEL(256, "iron_shovel", 1);
        const Item Items::IRON_PICKAXE(257, "iron_pickaxe", 1);
        const Item Items::IRON_AXE(258, "iron_axe", 1);
        const Item Items::FLINT_AND_STEEL(259, "flint_and_steel", 1);
        const Item Items::APPLE(260, "apple");
        const Item Items::BOW(261, "bow", 1);
        const Item Items::ARROW(262, "arrow");
        const Item Items::COAL(263, "coal");
        const Item Items::DIAMOND(264, "diamond");
        const Item Items::IRON_INGOT(265, "iron_ingot");
        const Item Items::GOLD_INGOT(266, "gold_ingot");
        const Item Items::STICK(280, "stick");
        const Item Items::BOWL(281, "bowl");
        const Item Items::MUSHROOM_STEW(282, "mushroom_stew", 1);
        const Item Items::GOLDEN_SWORD(283, "golden_sword", 1);
        const Item Items::GOLDEN_SHOVEL(284, "golden_shovel", 1);
        const Item Items::GOLDEN_PICKAXE(285, "golden_pickaxe", 1);
        const Item Items::GOLDEN_AXE(286, "golden_axe", 1);
        const Item Items::STRING(287, "string");
        const Item Items::FEATHER(288, "feather");
        const Item Items::GUNPOWDER(289, "gunpowder");
        const Item Items::WOODEN_HOE(290, "wooden_hoe", 1);
        const Item Items::STONE_HOE(291, "stone_hoe", 1);
        const Item Items::IRON_HOE(292, "iron_hoe", 1);
        const Item Items::DIAMOND_HOE(293, "diamond_hoe", 1);
        const Item Items::GOLDEN_HOE(294, "golden_hoe", 1);
        const Item Items::SEEDS(295, "wheat_seeds");
        const Item Items::WHEAT(296, "wheat");
        const Item Items::BREAD(297, "bread");
        const Item Items::LEATHER_HELMET(298, "leather_helmet", 1);
        const Item Items::LEATHER_CHESTPLATE(299, "leather_chestplate", 1);
        const Item Items::LEATHER_LEGGINGS(300, "leather_leggings", 1);
        const Item Items::LEATHER_BOOTS(301, "leather_boots", 1);
        const Item Items::CHAINMAIL_HELMET(302, "chainmail_helmet", 1);
        const Item Items::CHAINMAIL_CHESTPLATE(303, "chainmail_chestplate", 1);
        const Item Items::CHAINMAIL_LEGGINGS(304, "chainmail_leggings", 1);
        const Item Items::CHAINMAIL_BOOTS(305, "chainmail_boots", 1);
        const Item Items::IRON_HELMET(306, "iron_helmet", 1);
        const Item Items::IRON_CHESTPLATE(307, "iron_chestplate", 1);
        const Item Items::IRON_LEGGINGS(308, "iron_leggings", 1);
        const Item Items::IRON_BOOTS(309, "iron_boots", 1);
        const Item Items::DIAMOND_HELMET(310, "diamond_helmet", 1);
        const Item Items::DIAMOND_CHESTPLATE(311, "diamond_chestplate", 1);
        const Item Items::DIAMOND_LEGGINGS(312, "diamond_leggings", 1);
        const Item Items::DIAMOND_BOOTS(313, "diamond_boots", 1);
        const Item Items::GOLDEN_HELMET(314, "golden_helmet", 1);
        const Item Items::GOLDEN_CHESTPLATE(315, "golden_chestplate", 1);
        const Item Items::GOLDEN_LEGGINGS(316, "golden_leggings", 1);
        const Item Items::GOLDEN_BOOTS(317, "golden_boots", 1);
        const Item Items::FLINT(318, "flint");
        const Item Items::PORKCHOP(319, "porkchop");
        const Item Items::COOKED_PORKCHOP(320, "cooked_porkchop");
        const Item Items::PAINTING(321, "painting");
        const Item Items::GOLDEN_APPLE(322, "golden_apple");
        const Item Items::SIGN(323, "sign", 16);
        const Item Items::WOODEN_DOOR(324, "wooden_door");
        const Item Items::BUCKET(325, "bucket", 16);
        const Item Items::MINECART(328, "minecart", 1);
        const Item Items::SADDLE(329, "saddle", 1);
        const Item Items::IRON_DOOR(330, "iron_door");
        const Item Items::REDSTONE(331, "redstone");
        const Item Items::SNOWBALL(332, "snowball", 16);
        const Item Items::BOAT(333, "oak_boat", 1);
        const Item Items::LEATHER(334, "leather");
        const Item Items::MILK_BUCKET(335, "milk_bucket", 1);
        const Item Items::CLAY_BALL(337, "clay_ball");
        const Item Items::SUGAR_CANE(338, "sugar_cane");
        const Item Items::PAPER(339, "paper");
        const Item Items::BOOK(340, "book");
        const Item Items::SLIME_BALL(341, "slime_ball");
        const Item Items::CHEST_MINECART(342, "chest_minecart", 1);
        const Item Items::FURNACE_MINECART(343, "furnace_minecart", 1);
        const Item Items::EGG(344, "egg", 16);
        const Item Items::COMPASS(345, "compass");
        const Item Items::FISHING_ROD(346, "fishing_rod", 1);
        const Item Items::CLOCK(347, "clock");
        const Item Items::GLOWSTONE_DUST(348, "glowstone_dust");
        const Item Items::COD(349, "cod");
        const Item Items::COOKED_COD(350, "cooked_cod");
        const Item Items::DYE(351, "dye");
        const Item Items::BONE(352, "bone");
        const Item Items::SUGAR(353, "sugar");
        const Item Items::CAKE(354, "cake", 1);
        const Item Items::BED(355, "white_bed", 1);
        const Item Items::REPEATER(356, "repeater");
        const Item Items::COOKIE(357, "cookie");
        const Item Items::MAP(358, "filled_map");
        const Item Items::SHEARS(359, "shears", 1);
        const Item Items::MELON_SLICE(360, "melon_slice");
        const Item Items::PUMPKIN_SEEDS(361, "pumpkin_seeds");
        const Item Items::MELON_SEEDS(362, "melon_seeds");
        const Item Items::BEEF(363, "beef");
        const Item Items::COOKED_BEEF(364, "cooked_beef");
        const Item Items::CHICKEN(365, "chicken");
        const Item Items::COOKED_CHICKEN(366, "cooked_chicken");
        const Item Items::ROTTEN_FLESH(367, "rotten_flesh");
        const Item Items::ENDER_PEARL(368, "ender_pearl", 16);
        const Item Items::BLAZE_ROD(369, "blaze_rod");
        const Item Items::GHAST_TEAR(370, "ghast_tear");
        const Item Items::GOLD_NUGGET(371, "gold_nugget");
        const Item Items::NETHER_WART(372, "nether_wart");
        const Item Items::POTION(373, "potion", 1);
        const Item Items::GLASS_BOTTLE(374, "glass_bottle");
        const Item Items::SPIDER_EYE(375, "spider_eye");
        const Item Items::FERMENTED_SPIDER_EYE(376, "fermented_spider_eye");
        const Item Items::BLAZE_POWDER(377, "blaze_powder");
        const Item Items::MAGMA_CREAM(378, "magma_cream");
        const Item Items::BREWING_STAND(379, "brewing_stand");
        const Item Items::CAULDRON(380, "cauldron");
        const Item Items::ENDER_EYE(381, "ender_eye");
        const Item Items::SPECKLED_MELON(382, "glistering_melon_slice");
        const Item Items::SPAWN_EGG(383, "spawn_egg");
        const Item Items::EXPERIENCE_BOTTLE(384, "experience_bottle");
        const Item Items::FIRE_CHARGE(385, "fire_charge");
        const Item Items::WRITABLE_BOOK(386, "writable_book", 1);
        const Item Items::WRITTEN_BOOK(387, "written_book", 16);
        const Item Items::EMERALD(388, "emerald");
        const Item Items::ITEM_FRAME(389, "item_frame");
        const Item Items::FLOWER_POT(390, "flower_pot");
        const Item Items::CARROT(391, "carrot");
        const Item Items::POTATO(392, "potato");
        const Item Items::BAKED_POTATO(393, "baked_potato");
        const Item Items::POISONOUS_POTATO(394, "poisonous_potato");
        const Item Items::MAP_FILLED(395, "filled_map");
        const Item Items::GOLDEN_CARROT(396, "golden_carrot");
        const Item Items::SKELETON_SKULL(397, "skeleton_skull");
        const Item Items::WITHER_SKELETON_SKULL(398, "wither_skeleton_skull");
        const Item Items::ZOMBIE_HEAD(399, "zombie_head");
        const Item Items::CREEPER_HEAD(400, "creeper_head");
        const Item Items::DRAGON_HEAD(401, "dragon_head");
        const Item Items::CARROT_ON_A_STICK(402, "carrot_on_a_stick", 1);
        const Item Items::NETHER_STAR(403, "nether_star");
        const Item Items::PUMPKIN_PIE(404, "pumpkin_pie");
        const Item Items::FIREWORK_ROCKET(405, "firework_rocket");
        const Item Items::FIREWORK_STAR(406, "firework_star");
        const Item Items::ENCHANTED_BOOK(407, "enchanted_book", 1);
        const Item Items::COMPARATOR(408, "comparator");
        const Item Items::NETHER_BRICK(409, "nether_brick");
        const Item Items::QUARTZ(410, "quartz");
        const Item Items::TNT_MINECART(411, "tnt_minecart", 1);
        const Item Items::HOPPER_MINECART(412, "hopper_minecart", 1);
        const Item Items::PRISMARINE_SHARD(413, "prismarine_shard");
        const Item Items::PRISMARINE_CRYSTALS(414, "prismarine_crystals");
        const Item Items::RABBIT(415, "rabbit");
        const Item Items::COOKED_RABBIT(416, "cooked_rabbit");
        const Item Items::RABBIT_STEW(417, "rabbit_stew", 1);
        const Item Items::RABBIT_FOOT(418, "rabbit_foot");
        const Item Items::RABBIT_HIDE(419, "rabbit_hide");
        const Item Items::ARMOR_STAND(420, "armor_stand", 16);
        const Item Items::IRON_HORSE_ARMOR(421, "iron_horse_armor", 1);
        const Item Items::GOLDEN_HORSE_ARMOR(422, "golden_horse_armor", 1);
        const Item Items::DIAMOND_HORSE_ARMOR(423, "diamond_horse_armor", 1);
        const Item Items::LEAD(424, "lead");
        const Item Items::NAME_TAG(425, "name_tag");
        const Item Items::COMMAND_BLOCK_MINECART(426, "command_block_minecart", 1);
        const Item Items::MUTTON(427, "mutton");
        const Item Items::COOKED_MUTTON(428, "cooked_mutton");
        const Item Items::BANNER(429, "white_banner", 16);
        const Item Items::END_CRYSTAL(430, "end_crystal");
        const Item Items::SPRUCE_DOOR(431, "spruce_door");
        const Item Items::BIRCH_DOOR(432, "birch_door");
        const Item Items::JUNGLE_DOOR(433, "jungle_door");
        const Item Items::ACACIA_DOOR(434, "acacia_door");
        const Item Items::DARK_OAK_DOOR(435, "dark_oak_door");
        const Item Items::CHORUS_FRUIT(436, "chorus_fruit");
        const Item Items::POPPED_CHORUS_FRUIT(437, "popped_chorus_fruit");
        const Item Items::BEETROOT(438, "beetroot");
        const Item Items::BEETROOT_SEEDS(439, "beetroot_seeds");
        const Item Items::BEETROOT_SOUP(440, "beetroot_soup", 1);
        const Item Items::DRAGON_BREATH(441, "dragon_breath");
        const Item Items::SPLASH_POTION(442, "splash_potion", 1);
        const Item Items::SPECTRAL_ARROW(443, "spectral_arrow");
        const Item Items::TIPPED_ARROW(444, "tipped_arrow");
        const Item Items::LINGERING_POTION(445, "lingering_potion", 1);
        const Item Items::SHIELD(446, "shield", 1);
        const Item Items::ELYTRA(447, "elytra", 1);
        const Item Items::SPRUCE_BOAT(448, "spruce_boat", 1);
        const Item Items::BIRCH_BOAT(449, "birch_boat", 1);
        const Item Items::JUNGLE_BOAT(450, "jungle_boat", 1);
        const Item Items::ACACIA_BOAT(451, "acacia_boat", 1);
        const Item Items::DARK_OAK_BOAT(452, "dark_oak_boat", 1);
        const Item Items::TOTEM_OF_UNDYING(453, "totem_of_undying", 1);
        const Item Items::SHULKER_SHELL(454, "shulker_shell");
        const Item Items::IRON_NUGGET(455, "iron_nugget");
        const Item Items::KNOWLEDGE_BOOK(456, "knowledge_book", 1);
        const Item Items::DEBUG_STICK(457, "debug_stick", 1);
        const Item Items::MUSIC_DISC_13(458, "music_disc_13", 1);
        const Item Items::MUSIC_DISC_CAT(459, "music_disc_cat", 1);
        const Item Items::MUSIC_DISC_BLOCKS(460, "music_disc_blocks", 1);
        const Item Items::MUSIC_DISC_CHIRP(461, "music_disc_chirp", 1);
        const Item Items::MUSIC_DISC_FAR(462, "music_disc_far", 1);
        const Item Items::MUSIC_DISC_MALL(463, "music_disc_mall", 1);
        const Item Items::MUSIC_DISC_MELLOHI(464, "music_disc_mellohi", 1);
        const Item Items::MUSIC_DISC_STAL(465, "music_disc_stal", 1);
        const Item Items::MUSIC_DISC_STRAD(466, "music_disc_strad", 1);
        const Item Items::MUSIC_DISC_WARD(467, "music_disc_ward", 1);
        const Item Items::MUSIC_DISC_11(468, "music_disc_11", 1);
        const Item Items::MUSIC_DISC_WAIT(469, "music_disc_wait", 1);
        const Item Items::TRIDENT(470, "trident", 1);
        const Item Items::PHANTOM_MEMBRANE(471, "phantom_membrane");
        const Item Items::NAUTILUS_SHELL(472, "nautilus_shell");
        const Item Items::HEART_OF_THE_SEA(473, "heart_of_the_sea");
        const Item Items::CROSSBOW(474, "crossbow", 1);
        const Item Items::SUSPICIOUS_STEW(475, "suspicious_stew", 1);
        const Item Items::LOOM(476, "loom");
        const Item Items::FLOWER_BANNER_PATTERN(477, "flower_banner_pattern", 1);
        const Item Items::CREEPER_BANNER_PATTERN(478, "creeper_banner_pattern", 1);
        const Item Items::SKULL_BANNER_PATTERN(479, "skull_banner_pattern", 1);
        const Item Items::MOJANG_BANNER_PATTERN(480, "mojang_banner_pattern", 1);
        const Item Items::GLOBE_BANNER_PATTERN(481, "globe_banner_pattern", 1);
        const Item Items::PIGLIN_BANNER_PATTERN(482, "piglin_banner_pattern", 1);
        const Item Items::COMPOSTER(483, "composter");
        const Item Items::BARREL(484, "barrel");
        const Item Items::SMOKER(485, "smoker");
        const Item Items::BLAST_FURNACE(486, "blast_furnace");
        const Item Items::CARTOGRAPHY_TABLE(487, "cartography_table");
        const Item Items::FLETCHING_TABLE(488, "fletching_table");
        const Item Items::GRINDSTONE(489, "grindstone");
        const Item Items::LECTERN(490, "lectern");
        const Item Items::SMITHING_TABLE(491, "smithing_table");
        const Item Items::STONECUTTER(492, "stonecutter");
        const Item Items::BELL(493, "bell");
        const Item Items::LANTERN(494, "lantern");
        const Item Items::SOUL_LANTERN(495, "soul_lantern");
        const Item Items::SWEET_BERRIES(496, "sweet_berries");
        const Item Items::GLOW_BERRIES(497, "glow_berries");
        const Item Items::CAMPFIRE(498, "campfire");
        const Item Items::SOUL_CAMPFIRE(499, "soul_campfire");
        const Item Items::SHROOMLIGHT(500, "shroomlight");
        const Item Items::HONEYCOMB(501, "honeycomb");
        const Item Items::BEE_NEST(502, "bee_nest");
        const Item Items::BEEHIVE(503, "beehive");
        const Item Items::HONEY_BOTTLE(504, "honey_bottle", 16);
        const Item Items::HONEY_BLOCK(505, "honey_block");
        const Item Items::LODESTONE(506, "lodestone");
        const Item Items::NETHERITE_BLOCK(507, "netherite_block");
        const Item Items::ANCIENT_DEBRIS(508, "ancient_debris");
        const Item Items::TARGET(509, "target");
        const Item Items::CRYING_OBSIDIAN(510, "crying_obsidian");
        const Item Items::BLACKSTONE(511, "blackstone");
        const Item Items::BLACKSTONE_SLAB(512, "blackstone_slab");
        const Item Items::BLACKSTONE_STAIRS(513, "blackstone_stairs");
        const Item Items::GILDED_BLACKSTONE(514, "gilded_blackstone");
        const Item Items::POLISHED_BLACKSTONE(515, "polished_blackstone");
        const Item Items::POLISHED_BLACKSTONE_SLAB(516, "polished_blackstone_slab");
        const Item Items::POLISHED_BLACKSTONE_STAIRS(517, "polished_blackstone_stairs");
        const Item Items::CHISELED_POLISHED_BLACKSTONE(518, "chiseled_polished_blackstone");
        const Item Items::POLISHED_BLACKSTONE_BRICKS(519, "polished_blackstone_bricks");
        const Item Items::POLISHED_BLACKSTONE_BRICK_SLAB(520, "polished_blackstone_brick_slab");
        const Item Items::POLISHED_BLACKSTONE_BRICK_STAIRS(521, "polished_blackstone_brick_stairs");
        const Item Items::CRACKED_POLISHED_BLACKSTONE_BRICKS(522, "cracked_polished_blackstone_bricks");
        const Item Items::RESPAWN_ANCHOR(523, "respawn_anchor");
    }
}
